python manage.py test kidsbook/sls/ || exit 1
python manage.py test kidsbook/group/ || exit 1
python manage.py test kidsbook/user/ || exit 1
python manage.py test kidsbook/users/ || exit 1
python manage.py test kidsbook/batch/ || exit 1
python manage.py test kidsbook/post/ || exit 1
python manage.py test kidsbook/notification/ || exit 1
python manage.py test kidsbook/survey/ || exit 1
python manage.py test kidsbook/surveys/ || exit 1
python manage.py test kidsbook/game/ || exit 1
python manage.py test kidsbook/game_scene/ || exit 1
