export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const CREATE_LIKE = 'CREATE_LIKE';
export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST';
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS';
export const CREATE_LIKE_FAILURE = 'CREATE_LIKE_FAILURE';

export const CREATE_FLAG = 'CREATE_FLAG';
export const CREATE_FLAG_REQUEST = 'CREATE_FLAG_REQUEST';
export const CREATE_FLAG_SUCCESS = 'CREATE_FLAG_SUCCESS';
export const CREATE_FLAG_FAILURE = 'CREATE_FLAG_FAILURE';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const CREATE_COMMENT_LIKE = 'CREATE_COMMENT_LIKE';
export const CREATE_COMMENT_LIKE_REQUEST = 'CREATE_COMMENT_LIKE_REQUEST';
export const CREATE_COMMENT_LIKE_SUCCESS = 'CREATE_COMMENT_LIKE_SUCCESS';
export const CREATE_COMMENT_LIKE_FAILURE = 'CREATE_COMMENT_LIKE_FAILURE';

export const CREATE_COMMENT_FLAG = 'CREATE_COMMENT_FLAG';
export const CREATE_COMMENT_FLAG_REQUEST = 'CREATE_COMMENT_FLAG_REQUEST';
export const CREATE_COMMENT_FLAG_SUCCESS = 'CREATE_COMMENT_FLAG_SUCCESS';
export const CREATE_COMMENT_FLAG_FAILURE = 'CREATE_COMMENT_FLAG_FAILURE';

export const GET_USER = 'GET_USER';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const SWITCH_GROUP = 'SWITCH_GROUP';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const GET_ALL_MEMBERS_REQUEST = 'GET_ALL_MEMBERS_REQUEST';
export const GET_ALL_MEMBERS_SUCCESS = 'GET_ALL_MEMBERS_SUCCESS';
export const GET_ALL_MEMBERS_FAILURE = 'GET_ALL_MEMBERS_FAILURE';

export const GET_ALL_ANY_MEMBERS = 'GET_ALL_ANY_MEMBERS';
export const GET_ALL_ANY_MEMBERS_REQUEST = 'GET_ALL_ANY_MEMBERS_REQUEST';
export const GET_ALL_ANY_MEMBERS_SUCCESS = 'GET_ALL_ANY_MEMBERS_SUCCESS';
export const GET_ALL_ANY_MEMBERS_FAILURE = 'GET_ALL_ANY_MEMBERS_FAILURE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const ADD_USER_TO_GROUP_REQUEST = 'ADD_USER_TO_GROUP_REQUEST';
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_FAILURE = 'ADD_USER_TO_GROUP_FAILURE';

export const IMPORT_USERS = 'IMPORT_USERS';
export const IMPORT_USERS_REQUEST = 'IMPORT_USERS_REQUEST';
export const IMPORT_USERS_SUCCESS = 'IMPORT_USERS_SUCCESS';
export const IMPORT_USERS_FAILURE = 'IMPORT_USERS_FAILURE';

export const GET_ALL_VIRTUAL = 'GET_ALL_VIRTUAL';
export const GET_ALL_VIRTUAL_REQUEST = 'GET_ALL_VIRTUAL_REQUEST';
export const GET_ALL_VIRTUAL_SUCCESS = 'GET_ALL_VIRTUAL_SUCCESS';
export const GET_ALL_VIRTUAL_FAILURE = 'GET_ALL_VIRTUAL_FAILURE';

export const SWITCH_USER = 'SWITCH_USER';
export const SWITCH_USER_REQUEST = 'SWITCH_USER_REQUEST';
export const SWITCH_USER_SUCCESS = 'SWITCH_USER_SUCCESS';
export const SWITCH_USER_FAILURE = 'SWITCH_USER_FAILURE';

export const ADD_USERS_TO_GROUP = 'ADD_USERS_TO_GROUP';
export const ADD_USERS_TO_GROUP_REQUEST = 'ADD_USERS_TO_GROUP_REQUEST';
export const ADD_USERS_TO_GROUP_SUCCESS = 'ADD_USERS_TO_GROUP_SUCCESS';
export const ADD_USERS_TO_GROUP_FAILURE = 'ADD_USERS_TO_GROUP_FAILURE';

export const GET_ALL_FLAGGED = 'GET_ALL_FLAGGED';
export const GET_ALL_FLAGGED_REQUEST = 'GET_ALL_FLAGGED_REQUEST';
export const GET_ALL_FLAGGED_SUCCESS = 'GET_ALL_FLAGGED_SUCCESS';
export const GET_ALL_FLAGGED_FAILURE = 'GET_ALL_FLAGGED_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_SUBCRIBE = 'SOCKET_SUBCRIBE';
export const SOCKET_UNSUBSCRIBE = 'SOCKET_UNSUBSCRIBE';
export const SOCKET_POST_UPDATE = 'SOCKET_POST_UPDATE';
export const SOCKET_COMMENT_UPDATE = 'SOCKET_COMMENT_UPDATE';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const SEEN_NOTIFICATIONS = 'SEEN_NOTIFICATIONS';

export const GET_POST = 'GET_POST';
export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE';

export const CREATE_SURVEY = 'CREATE_SURVEY';
export const CREATE_SURVEY_REQUEST = 'CREATE_SURVEY_REQUEST';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const CREATE_SURVEY_FAILURE = 'CREATE_SURVEY_FAILURE';

export const GET_ALL_SURVEYS = 'GET_ALL_SURVEYS';
export const GET_ALL_SURVEYS_REQUEST = 'GET_ALL_SURVEYS_REQUEST';
export const GET_ALL_SURVEYS_SUCCESS = 'GET_ALL_SURVEYS_SUCCESS';
export const GET_ALL_SURVEYS_FAILURE = 'GET_ALL_SURVEYS_FAILURE';

export const GET_ALL_INCOMPLETE_SURVEYS = 'GET_ALL_INCOMPLETE_SURVEYS';
export const GET_ALL_INCOMPLETE_SURVEYS_REQUEST = 'GET_ALL_INCOMPLETE_SURVEYS_REQUEST';
export const GET_ALL_INCOMPLETE_SURVEYS_SUCCESS = 'GET_ALL_INCOMPLETE_SURVEYS_SUCCESS';
export const GET_ALL_INCOMPLETE_SURVEYS_FAILURE = 'GET_ALL_INCOMPLETE_SURVEYS_FAILURE';

export const OPEN_INCOMPLETE_SURVEY = 'OPEN_INCOMPLETE_SURVEY';

export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEY_REQUEST = 'GET_SURVEY_REQUEST';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_FAILURE = 'GET_SURVEY_FAILURE';

export const GET_SURVEY_ANSWER = 'GET_SURVEY_ANSWER';
export const GET_SURVEY_ANSWER_REQUEST = 'GET_SURVEY_ANSWER_REQUEST';
export const GET_SURVEY_ANSWER_SUCCESS = 'GET_SURVEY_ANSWER_SUCCESS';
export const GET_SURVEY_ANSWER_FAILURE = 'GET_SURVEY_ANSWER_FAILURE';

export const GET_ALL_SURVEY_ANSWER = 'GET_ALL_SURVEY_ANSWER';
export const GET_ALL_SURVEY_ANSWER_REQUEST = 'GET_ALL_SURVEY_ANSWER_REQUEST';
export const GET_ALL_SURVEY_ANSWER_SUCCESS = 'GET_ALL_SURVEY_ANSWER_SUCCESS';
export const GET_ALL_SURVEY_ANSWER_FAILURE = 'GET_ALL_SURVEY_ANSWER_FAILURE';

export const SUBMIT_SURVEY_ANSWER = 'SUBMIT_SURVEY_ANSWER';
export const SUBMIT_SURVEY_ANSWER_REQUEST = 'SUBMIT_SURVEY_ANSWER_REQUEST';
export const SUBMIT_SURVEY_ANSWER_SUCCESS = 'SUBMIT_SURVEY_ANSWER_SUCCESS';
export const SUBMIT_SURVEY_ANSWER_FAILURE = 'SUBMIT_SURVEY_ANSWER_FAILURE';

export const CLEAR_ALL_SURVEY_ANSWER = 'CLEAR_ALL_SURVEY_ANSWER';
export const CLEAR_ALL_SURVEY_ANSWER_REQUEST = 'CLEAR_ALL_SURVEY_ANSWER_REQUEST';
export const CLEAR_ALL_SURVEY_ANSWER_SUCCESS = 'CLEAR_ALL_SURVEY_ANSWER_SUCCESS';
export const CLEAR_ALL_SURVEY_ANSWER_FAILURE = 'CLEAR_ALL_SURVEY_ANSWER_FAILURE';

export const UPDATE_SURVEY = 'UPDATE_SURVEY';
export const UPDATE_SURVEY_REQUEST = 'UPDATE_SURVEY_REQUEST';
export const UPDATE_SURVEY_SUCCESS = 'UPDATE_SURVEY_SUCCESS';
export const UPDATE_SURVEY_FAILURE = 'UPDATE_SURVEY_FAILURE';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

export const DELETE_SURVEY = 'DELETE_SURVEY';
export const DELETE_SURVEY_REQUEST = 'DELETE_SURVEY_REQUEST';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_FAILURE = 'DELETE_SURVEY_FAILURE';

export const UPLOAD_GAME = 'UPLOAD_GAME';
export const UPLOAD_GAME_REQUEST = 'UPLOAD_GAME_REQUEST';
export const UPLOAD_GAME_SUCCESS = 'UPLOAD_GAME_SUCCESS';
export const UPLOAD_GAME_FAILURE = 'UPLOAD_GAME_FAILURE';

export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_ALL_GAMES_REQUEST = 'GET_ALL_GAMES_REQUEST';
export const GET_ALL_GAMES_SUCCESS = 'GET_ALL_GAMES_SUCCESS';
export const GET_ALL_GAMES_FAILURE = 'GET_ALL_GAMES_FAILURE';

export const GET_GAME_NEXT_SCENE = 'GET_GAME_NEXT_SCENE';
export const GET_GAME_NEXT_SCENE_REQUEST = 'GET_GAME_NEXT_SCENE_REQUEST';
export const GET_GAME_NEXT_SCENE_SUCCESS = 'GET_GAME_NEXT_SCENE_SUCCESS';
export const GET_GAME_NEXT_SCENE_FAILURE = 'GET_GAME_NEXT_SCENE_FAILURE';

export const UPDATE_GAME_ANSWER = 'UPDATE_GAME_ANSWER';
export const UPDATE_GAME_ANSWER_REQUEST = 'UPDATE_GAME_ANSWER_REQUEST';
export const UPDATE_GAME_ANSWER_SUCCESS = 'UPDATE_GAME_ANSWER_SUCCESS';
export const UPDATE_GAME_ANSWER_FAILURE = 'UPDATE_GAME_ANSWER_FAILURE';

export const GET_GAME = 'GET_GAME';
export const GET_GAME_REQUEST = 'GET_GAME_REQUEST';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_FAILURE = 'GET_GAME_FAILURE';

export const GET_GAME_ANSWER = 'GET_GAME_ANSWER';
export const GET_GAME_ANSWER_REQUEST = 'GET_GAME_ANSWER_REQUEST';
export const GET_GAME_ANSWER_SUCCESS = 'GET_GAME_ANSWER_SUCCESS';
export const GET_GAME_ANSWER_FAILURE = 'GET_GAME_ANSWER_FAILURE';

export const DELETE_GAME = 'DELETE_GAME';
export const DELETE_GAME_REQUEST = 'DELETE_GAME_REQUEST';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';

export const PUSH_NEW_ACTION = 'PUSH_NEW_ACTION';
export const PUSH_NEW_ACTION_REQUEST = 'PUSH_NEW_ACTION_REQUEST';
export const PUSH_NEW_ACTION_SUCCESS = 'PUSH_NEW_ACTION_SUCCESS';
export const PUSH_NEW_ACTION_FAILURE = 'PUSH_NEW_ACTION_FAILURE';

export const UPDATE_ACTION = 'UPDATE_ACTION';
export const UPDATE_ACTION_REQUEST = 'UPDATE_ACTION_REQUEST';
export const UPDATE_ACTION_SUCCESS = 'UPDATE_ACTION_SUCCESS';
export const UPDATE_ACTION_FAILURE = 'UPDATE_ACTION_FAILURE';

export const SOCKET_PUSHACTIONS = 'SOCKET_PUSHACTIONS';
